# Copyright (c) 2026, mehmehsloth and contributors
# For license information, please see license.txt
#
# Context for the SPA shell (frontend.html, generated by the frontend build).
# Mirrors the canonical frappe-ui pattern (see ../crm/crm/www/crm.py): the built
# HTML is a Jinja template, and get_context supplies the values it references.
# Guest access is allowed so public/unlisted snippets render without login.

import frappe

no_cache = 1


def get_context(context):
	# The shell embeds `window.csrf_token = '{{ csrf_token }}'`; supply a real token
	# so logged-in users can POST. Guests get a token too (harmless).
	context.csrf_token = frappe.sessions.get_csrf_token()
	frappe.db.commit()
	return context
